# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ClusterClikcpp <- function(Rmat, R) {
    .Call(`_SeriClustR_ClusterClikcpp`, Rmat, R)
}

PhiClustercpp <- function(mat, R, k) {
    .Call(`_SeriClustR_PhiClustercpp`, mat, R, k)
}

